/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ioc.dam.m13.tutor_finder.desktop;

import javax.swing.JOptionPane;
import ioc.dam.m13.tutor_finder.client.TFClient;
import ioc.dam.m13.tutor_finder.client.TFClientImple;
import ioc.dam.m13.tutor_finder.dtos.UserDTO;
import java.security.MessageDigest;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Alexandre
 */
public class canvi_ContrasenyaProfessor extends javax.swing.JFrame {

    /**
     * Creates new form canvi_Contrasenya
     */
    public canvi_ContrasenyaProfessor() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitol = new javax.swing.JLabel();
        buttonTornar = new javax.swing.JButton();
        labelContrasenya2 = new javax.swing.JLabel();
        textContrasenyaNova = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        labelROl = new javax.swing.JLabel();
        labelUsuari = new javax.swing.JLabel();
        textUsuari = new javax.swing.JTextField();
        buttonCanviar = new javax.swing.JButton();
        fons = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitol.setFont(new java.awt.Font("Gigi", 0, 105)); // NOI18N
        labelTitol.setText("TutorFinder");
        getContentPane().add(labelTitol, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 540, 90));

        buttonTornar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonTornar.setText("Tornar");
        buttonTornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTornarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonTornar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 570, 120, 30));

        labelContrasenya2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelContrasenya2.setText("Nova contrasenya: ");
        getContentPane().add(labelContrasenya2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, -1, -1));

        textContrasenyaNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textContrasenyaNovaActionPerformed(evt);
            }
        });
        getContentPane().add(textContrasenyaNova, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 240, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ioc/dam/m13/tutor_finder/desktop/canvi contrasenya.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 330, -1, -1));

        labelROl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelROl.setText("Tutor");
        getContentPane().add(labelROl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 610, 100, -1));

        labelUsuari.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelUsuari.setText("Nom Usuari: ");
        getContentPane().add(labelUsuari, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 150, -1));
        getContentPane().add(textUsuari, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 410, 240, -1));

        buttonCanviar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonCanviar.setText("Canviar");
        buttonCanviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCanviarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCanviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 570, 120, 30));

        fons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ioc/dam/m13/tutor_finder/desktop/fondo.jpg"))); // NOI18N
        getContentPane().add(fons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 480, 230, -1));

        jTextField2.setText("jTextField2");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 450, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTornarActionPerformed
        // TODO add your handling code here:
        //Tornar a la pantalla principal tutor
        menuPrincipalProfessor formMenuClient = new menuPrincipalProfessor();
        formMenuClient.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonTornarActionPerformed

    private void textContrasenyaNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textContrasenyaNovaActionPerformed
        // TODO add your handling code here:
        //Controlar que la contrasenya ha de contenir minim 6 caracters
        int numero=5;
        char clave[]=textContrasenyaNova.getPassword();
        String clavedef=new String(clave);        
        if (clavedef.length()<=numero){
            //evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ha de contenir 6 caracters o mes");
        }
    }//GEN-LAST:event_textContrasenyaNovaActionPerformed

    //Metode per cnriptar l'string que se li passa
    public static String md5(String clear) throws Exception {
    MessageDigest md = MessageDigest.getInstance("MD5");
    byte[] b = md.digest(clear.getBytes());
    int size = b.length;
    StringBuffer h = new StringBuffer(size);
        for (int i = 0; i < size; i++) {
            int u = b[i] & 255;
                if (u < 16) {
                    h.append("0" + Integer.toHexString(u));
                }
               else {
                    h.append(Integer.toHexString(u));
               }
           }
      //clau encriptada
      return h.toString();
    }
    
    private void buttonCanviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCanviarActionPerformed
        // TODO add your handling code here:
        //Fem la connexio per canviar la contrasenya
        TFClient client = new TFClientImple();
        UserDTO userDTO = null;
        //Variables per encriptar la contrasenya
        char clave[]=textContrasenyaNova.getPassword();
        String clavedef=new String(clave);
        try {
            clavedef = md5(textContrasenyaNova.getText());
            System.out.println("Encriptat: "+clavedef);
        } catch (Exception ex) {
            Logger.getLogger(canvi_ContrasenyaProfessor.class.getName()).log(Level.SEVERE, null, ex);
        }
        String usuari = textUsuari.getText();
        //Retorna true o false al canviar contrasenya
        boolean ret = client.editUserPswd(usuari, clavedef);
        
        if (ret) {
            if(usuari.equals("") || usuari.equals("null") || clavedef.equals("") || clavedef.equals("null")){
                JOptionPane.showMessageDialog(rootPane, "Error al canviar la contrasenya");
                System.out.println("Error al canviar la contrasenya");
                }
        else {
                userDTO = client.userData(usuari);
                System.out.println("CLAVEDEF2: "+ clavedef);

                System.out.println(userDTO.toString());
                JOptionPane.showMessageDialog(rootPane, "Contrasenya Canviada");
                System.out.println("Contrasenya canviada");  
            }
        }
    }//GEN-LAST:event_buttonCanviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(canvi_ContrasenyaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(canvi_ContrasenyaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(canvi_ContrasenyaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(canvi_ContrasenyaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new canvi_ContrasenyaProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCanviar;
    private javax.swing.JButton buttonTornar;
    private javax.swing.JLabel fons;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel labelContrasenya2;
    private javax.swing.JLabel labelROl;
    private javax.swing.JLabel labelTitol;
    private javax.swing.JLabel labelUsuari;
    private javax.swing.JPasswordField textContrasenyaNova;
    private javax.swing.JTextField textUsuari;
    // End of variables declaration//GEN-END:variables
}
