/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ioc.dam.m13.tutor_finder.desktop;

import ioc.dam.m13.tutor_finder.client.TFClient;
import ioc.dam.m13.tutor_finder.client.TFClientImple;
import ioc.dam.m13.tutor_finder.dtos.AdDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alexandre
 */
public class gestioPublicacions extends javax.swing.JFrame {
        //variable per saber quina fila de la taula s'ha seleccionat
        int filaSeleccionada = -1;        
        //variable per saber el nom del usuari que ha accedit
        String userName;
    /**
     * Creates new form menuPrincipal
     */
    public gestioPublicacions() {
        initComponents();
        //Metode per mostrar taula amb les publicacions
        mostrarPublicacionsTaula();
        //variable per saber quin user id ha accedit a l'aplicació
        int UserID = login.UserID;
        //per saber el nom del usuari que ha accedit a l'aplicació
        userName = login.usuari;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /**
     * Al initComponents tenim els titols i botons de la part del Menu Usuari
     * */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelROl = new javax.swing.JLabel();
        buttonTornar = new javax.swing.JButton();
        labelTitol = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        labelPublicacions3 = new javax.swing.JLabel();
        labelPublicacions = new javax.swing.JLabel();
        buttonTotes = new javax.swing.JButton();
        buttornEliminar = new javax.swing.JButton();
        ComboBoxRole = new javax.swing.JComboBox<>();
        ComboBoxCategoria = new javax.swing.JComboBox<>();
        labelPublicacions1 = new javax.swing.JLabel();
        buttonMostrarPublicacions = new javax.swing.JButton();
        fons = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelROl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelROl.setText("Admin");
        getContentPane().add(labelROl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 610, -1, -1));

        buttonTornar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonTornar.setText("Tornar");
        buttonTornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTornarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonTornar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 600, 120, 30));

        labelTitol.setFont(new java.awt.Font("Gigi", 0, 105)); // NOI18N
        labelTitol.setText("TutorFinder");
        getContentPane().add(labelTitol, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 540, 90));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Titol", "Descripció", "Categoria", "Preu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 700, 260));

        labelPublicacions3.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 24)); // NOI18N
        labelPublicacions3.setForeground(new java.awt.Color(0, 0, 204));
        labelPublicacions3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPublicacions3.setText("Publicacions:");
        getContentPane().add(labelPublicacions3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 270, -1));

        labelPublicacions.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 18)); // NOI18N
        labelPublicacions.setForeground(new java.awt.Color(0, 0, 204));
        labelPublicacions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPublicacions.setText("Llistar per Role:");
        getContentPane().add(labelPublicacions, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 460, 190, -1));

        buttonTotes.setText("Totes");
        buttonTotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTotesActionPerformed(evt);
            }
        });
        getContentPane().add(buttonTotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 400, 130, -1));

        buttornEliminar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttornEliminar.setText("Eliminar");
        buttornEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttornEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(buttornEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 540, 80, -1));

        ComboBoxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "          ", "tutor", "student" }));
        ComboBoxRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxRoleActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBoxRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 490, 130, -1));

        ComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                      ", "Física/Química", "Idiomes", "Informàtica", "Electricitat/Mecànica", "Dibuix", "Economía", "Arts escéniques", "Mùsica" }));
        ComboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBoxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 430, 130, -1));

        labelPublicacions1.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 18)); // NOI18N
        labelPublicacions1.setForeground(new java.awt.Color(0, 0, 204));
        labelPublicacions1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPublicacions1.setText("Llistar per categoria:");
        getContentPane().add(labelPublicacions1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 370, 200, -1));

        buttonMostrarPublicacions.setText("Mostrar Publicació ");
        buttonMostrarPublicacions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMostrarPublicacionsActionPerformed(evt);
            }
        });
        getContentPane().add(buttonMostrarPublicacions, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 350, -1, -1));

        fons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ioc/dam/m13/tutor_finder/desktop/fondo.jpg"))); // NOI18N
        getContentPane().add(fons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Botó per sortir de l'aplicació
     * */
    private void buttonTornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTornarActionPerformed
        // TODO add your handling code here:
        //Boto per tornar a la pantalla principal administrador
        menuPrincipalAdmin formMenuAdmin = new menuPrincipalAdmin();
        formMenuAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonTornarActionPerformed

    private void ComboBoxRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxRoleActionPerformed
        // TODO add your handling code here:
        //Fem la connexió amb la classe que es connecta amb el servidor
        TFClient l = new TFClientImple();
        String user = ComboBoxRole.getSelectedItem().toString();
        int userId = l.getUserRoleId(user);
        DefaultTableModel modelo = new DefaultTableModel();
            jTable2.setModel(modelo);

                modelo.addColumn("Ad id");
                modelo.addColumn("Titol");
                modelo.addColumn("Descripcio");
                modelo.addColumn("Categoria");
                modelo.addColumn("Preu");
                modelo.addColumn("Usuari");
                
                //Aqui mostrem a la taula les publicacions per el role de l'usuari
                ArrayList<AdDTO> ads = l.listAdsByRole(userId);
                for (AdDTO ad : ads) {
                System.out.println("----- Ads -----");
                System.out.println(ad.toString());
                System.out.println("--------------------");
                    Object []ob=new Object[6];
                    ob[0]=(ad.getAdId());
                    ob[1]=(ad.getAdTittle());
                    ob[2]=(ad.getAdDescription());
                    ob[3]=(ad.getTypesName());
                    ob[4]=(ad.getAdPrice());
                    ob[5]=(ad.getUserName());
                    //afegeixo el model a la taula
                    modelo.addRow(ob);
                } 
    }//GEN-LAST:event_ComboBoxRoleActionPerformed

    private void ComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxCategoriaActionPerformed
        // TODO add your handling code here:
        //Fem la connexió amb la classe que es connecta amb el servidor
        TFClient l = new TFClientImple();
        String tipus = ComboBoxCategoria.getSelectedItem().toString();
        int typeId = l.getAdTypeByName(tipus);
         DefaultTableModel modelo = new DefaultTableModel();
                jTable2.setModel(modelo);

                modelo.addColumn("Ad id");
                modelo.addColumn("Titol");
                modelo.addColumn("Descripcio");
                modelo.addColumn("Categoria");
                modelo.addColumn("Preu");
                modelo.addColumn("Usuari");
                
                //Aqui mostrem a la taula les publicacions per la categoria seleccionada
                ArrayList<AdDTO> ads = l.listAdsByType(typeId);
                for (AdDTO ad : ads) {
                System.out.println("----- Ads -----");
                System.out.println(ad.toString());
                System.out.println("--------------------");
                    Object []ob=new Object[6];
                    ob[0]=(ad.getAdId());
                    ob[1]=(ad.getAdTittle());
                    ob[2]=(ad.getAdDescription());
                    ob[3]=(ad.getTypesName());
                    ob[4]=(ad.getAdPrice());
                    ob[5]=(ad.getUserName());
                    //afegeixo el model a la taula
                    modelo.addRow(ob);
                } 
    }//GEN-LAST:event_ComboBoxCategoriaActionPerformed

    private void buttonTotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTotesActionPerformed
        // TODO add your handling code here:
        //Boto que mostrara a la taula totes les publicacions independentment de la categoria o role de l'usuari
        mostrarPublicacionsTaula();
    }//GEN-LAST:event_buttonTotesActionPerformed

    private void buttornEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttornEliminarActionPerformed
        // TODO add your handling code here:
        //Fem la connexió amb la classe que es connecta amb el servidor
        TFClient l = new TFClientImple();
        ArrayList<AdDTO> ads = l.listAds();
        //variable per guardar el id de l'anunci de la fila seleccionada
        int identificador = 0;
        for (Object ad : ads) {
            System.out.println(ad.toString());
        }
        int filaSeleccionada = this.jTable2.getSelectedRow();
        if(filaSeleccionada>=0){
                    //Recullim el id de la fila marcada
                    identificador   = (int) jTable2.getValueAt(filaSeleccionada, 0);
                }
        boolean ret = l.delAd(identificador);
        //Si ens retorna true l'usuari eliminem l'usuari de la taula i la base de dades
        if (ret) {
            //Eliminar anunci seleccionat a la taula
            DefaultTableModel m = (DefaultTableModel) jTable2.getModel();
            m.removeRow(filaSeleccionada);
            JOptionPane.showMessageDialog(rootPane, "S'ha eliminat l'anunci satisfactoriament.");
            System.out.println("S'ha eliminat l'anunci satisfactoriament.");
        } else {
            JOptionPane.showMessageDialog(rootPane, "NO s'ha eliminat l'anunci satisfactoriament.");
            System.out.println("NO s'ha eliminat l'anunci.");
        }
    }//GEN-LAST:event_buttornEliminarActionPerformed

    private void buttonMostrarPublicacionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMostrarPublicacionsActionPerformed
        // TODO add your handling code here:
        //boto que ens mostrara la publicació per poder-la llegir al complert
        mostrarPublicacio m = new mostrarPublicacio();
        this.dispose();
        filaSeleccionada = jTable2.getSelectedRow();
        m.textTitol.setText(jTable2.getValueAt(filaSeleccionada,1).toString());;
        m.jTextAreaDescripcio.setText(jTable2.getValueAt(filaSeleccionada,2).toString());
        m.comboCategoria.setSelectedItem(jTable2.getValueAt(filaSeleccionada,3).toString());
        m.textPreu.setText(jTable2.getValueAt(filaSeleccionada,4).toString());
        m.show();
    }//GEN-LAST:event_buttonMostrarPublicacionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestioPublicacions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestioPublicacions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestioPublicacions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestioPublicacions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestioPublicacions().setVisible(true);
            }
        });
    }
    
    //Metode que mostra els anuncis nomes entrar a la pantalla del menu principal de admin.
    private void mostrarPublicacionsTaula() {
         TFClient l = new TFClientImple();
         DefaultTableModel modelo = new DefaultTableModel();
                jTable2.setModel(modelo);
                modelo.addColumn("Ad id");
                modelo.addColumn("Titol");
                modelo.addColumn("Descripcio");
                modelo.addColumn("Categoria");
                modelo.addColumn("Preu");
                modelo.addColumn("Usuari");
                //Aqui mostrem a la taula les publicacions de tots els anuncis
                ArrayList<AdDTO> ads = l.listAds();
                for (AdDTO ad : ads) {
                System.out.println("----- Ads -----");
                System.out.println(ad.toString());
                System.out.println("--------------------");
                    Object []ob=new Object[6];
                    ob[0]=(ad.getAdId());
                    ob[1]=(ad.getAdTittle());
                    ob[2]=(ad.getAdDescription());
                    ob[3]=(ad.getTypesName());
                    ob[4]=(ad.getAdPrice());
                    ob[5]=(ad.getUserName());
                    //aafegeixo el model a la taula
                    modelo.addRow(ob);
                }             
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxCategoria;
    private javax.swing.JComboBox<String> ComboBoxRole;
    private javax.swing.JButton buttonMostrarPublicacions;
    private javax.swing.JButton buttonTornar;
    private javax.swing.JButton buttonTotes;
    private javax.swing.JButton buttornEliminar;
    private javax.swing.JLabel fons;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelPublicacions;
    private javax.swing.JLabel labelPublicacions1;
    private javax.swing.JLabel labelPublicacions3;
    private javax.swing.JLabel labelROl;
    private javax.swing.JLabel labelTitol;
    // End of variables declaration//GEN-END:variables
}
