/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ioc.dam.m13.tutor_finder.desktop;

import ioc.dam.m13.tutor_finder.client.TFClient;
import ioc.dam.m13.tutor_finder.client.TFClientImple;
import ioc.dam.m13.tutor_finder.dtos.UserDTO;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alexandre
 */
public class gestioUsuaris extends javax.swing.JFrame {
    //variable per saber quina fila de la taula s'ha seleccionat
    int filaSeleccionada = -1;
    /**
     * Creates new form gestioUsuaris
     */
    public gestioUsuaris() {
        initComponents();
        //Metode que mostra tots els usuaris 
        mostrarUsuarisTaula();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitol = new javax.swing.JLabel();
        buttonTornar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        buttonNou = new javax.swing.JButton();
        buttonRegistrar = new javax.swing.JButton();
        buttonModificar = new javax.swing.JButton();
        buttonEliminar = new javax.swing.JButton();
        buttonOrdenarAdmin = new javax.swing.JButton();
        labelNomusuari = new javax.swing.JLabel();
        textNomusuari = new javax.swing.JTextField();
        labelContrasenya = new javax.swing.JLabel();
        textContrasenya = new javax.swing.JPasswordField();
        labelEmail = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        labelTipusUsuari = new javax.swing.JLabel();
        tipusUsuari = new javax.swing.JComboBox<>();
        icon = new javax.swing.JLabel();
        buttonOrdenarTutor = new javax.swing.JButton();
        buttonOrdenarStudent = new javax.swing.JButton();
        labelOrdenar = new javax.swing.JLabel();
        buttonOrdenarUsers = new javax.swing.JButton();
        textCercarUsuari = new javax.swing.JTextField();
        labelCercar = new javax.swing.JLabel();
        buttonCercar = new javax.swing.JButton();
        carregarDades = new javax.swing.JButton();
        buttonCanviar = new javax.swing.JButton();
        fons = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitol.setFont(new java.awt.Font("Gigi", 0, 105)); // NOI18N
        labelTitol.setText("TutorFinder");
        getContentPane().add(labelTitol, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 540, 90));

        buttonTornar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonTornar.setText("Tornar");
        buttonTornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTornarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonTornar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 610, 120, 30));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "USUARI", "EMAIL", "TIPUS USUARI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 500, 200));

        buttonNou.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonNou.setText("Nou");
        buttonNou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNouActionPerformed(evt);
            }
        });
        getContentPane().add(buttonNou, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 70, -1));

        buttonRegistrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonRegistrar.setText("Registrar");
        buttonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 360, 100, -1));

        buttonModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonModificar.setText("Modificar");
        buttonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModificarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, 100, -1));

        buttonEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonEliminar.setText("Eliminar");
        buttonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 360, 100, -1));

        buttonOrdenarAdmin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonOrdenarAdmin.setText("Admin");
        buttonOrdenarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOrdenarAdminActionPerformed(evt);
            }
        });
        getContentPane().add(buttonOrdenarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 320, 80, 30));

        labelNomusuari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelNomusuari.setText("Nom usuari: ");
        getContentPane().add(labelNomusuari, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, -1, -1));

        textNomusuari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomusuariActionPerformed(evt);
            }
        });
        getContentPane().add(textNomusuari, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 190, -1));

        labelContrasenya.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelContrasenya.setText("Contrasenya: ");
        getContentPane().add(labelContrasenya, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, -1, -1));

        textContrasenya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textContrasenyaActionPerformed(evt);
            }
        });
        getContentPane().add(textContrasenya, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 190, -1));

        labelEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelEmail.setText("E-mail: ");
        getContentPane().add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, -1, -1));

        textEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmailActionPerformed(evt);
            }
        });
        getContentPane().add(textEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, 190, -1));

        labelTipusUsuari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTipusUsuari.setText("Tipus d'usuari: ");
        getContentPane().add(labelTipusUsuari, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, -1, -1));

        tipusUsuari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                    ", "admin", "tutor", "student" }));
        getContentPane().add(tipusUsuari, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 190, -1));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ioc/dam/m13/tutor_finder/desktop/registre usuari.png"))); // NOI18N
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 140, 140));

        buttonOrdenarTutor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonOrdenarTutor.setText("Tutor");
        buttonOrdenarTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOrdenarTutorActionPerformed(evt);
            }
        });
        getContentPane().add(buttonOrdenarTutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 320, 80, 30));

        buttonOrdenarStudent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonOrdenarStudent.setText("Student");
        buttonOrdenarStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOrdenarStudentActionPerformed(evt);
            }
        });
        getContentPane().add(buttonOrdenarStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 320, -1, 30));

        labelOrdenar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelOrdenar.setText("Prem el botó per Llistar per role: ");
        getContentPane().add(labelOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 290, -1, -1));

        buttonOrdenarUsers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonOrdenarUsers.setText("Llistar Usuaris");
        buttonOrdenarUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOrdenarUsersActionPerformed(evt);
            }
        });
        getContentPane().add(buttonOrdenarUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 360, 130, -1));
        getContentPane().add(textCercarUsuari, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 100, 30));

        labelCercar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelCercar.setText("Introdueix l'usuari a cercar: ");
        getContentPane().add(labelCercar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 230, -1));

        buttonCercar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonCercar.setText("Cercar");
        buttonCercar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCercarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCercar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 320, -1, 30));

        carregarDades.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        carregarDades.setText("Carregar Dades");
        carregarDades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carregarDadesActionPerformed(evt);
            }
        });
        getContentPane().add(carregarDades, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, -1, -1));

        buttonCanviar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonCanviar.setText("Canviar Contrasenya");
        buttonCanviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCanviarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCanviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 435, 180, -1));

        fons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ioc/dam/m13/tutor_finder/desktop/fondo.jpg"))); // NOI18N
        getContentPane().add(fons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTornarActionPerformed
        // TODO add your handling code here:
        //Tornem al menu principal admin
        menuPrincipalAdmin formMenuAdmin = new menuPrincipalAdmin();
        formMenuAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonTornarActionPerformed

    private void textEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmailActionPerformed
        // TODO add your handling code here:
        //Controlar que el format del email sigui correcte
        Pattern pattern = Pattern
                .compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        Matcher mather = pattern.matcher(textEmail.getText());
 
        if (mather.find() == true) {
            System.out.println("El email ingresado es válido.");
            JOptionPane.showMessageDialog(rootPane, "El email introduit es correcte.");
        } else {
            System.out.println("El email ingresado es inválido.");
            JOptionPane.showMessageDialog(rootPane, "El email introduit NO es correcte.");
        }
    
    }//GEN-LAST:event_textEmailActionPerformed

    private void buttonNouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNouActionPerformed
        // TODO add your handling code here:
        //Fiquem en blanc els camps per crear un nou usuari
                this.textNomusuari.setText("");
                this.textContrasenya.setText("");
                this.textEmail.setText("");
                this.tipusUsuari.setSelectedItem("");       
    }//GEN-LAST:event_buttonNouActionPerformed

    private void textContrasenyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textContrasenyaActionPerformed
        // TODO add your handling code here:
        //Controlar que la contrasenya ha de contenir minim 6 caracters
        int numero=5;
        char clave[]=textContrasenya.getPassword();
        String clavedef=new String(clave);        
        if (clavedef.length()<=numero){
            //evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ha de contenir 6 caracters o mes");
        }
    }//GEN-LAST:event_textContrasenyaActionPerformed

    //Metode per encriptar l'String que passem
    public static String md5(String clear) throws Exception {
    MessageDigest md = MessageDigest.getInstance("MD5");
    byte[] b = md.digest(clear.getBytes());
    int size = b.length;
    StringBuffer h = new StringBuffer(size);
        for (int i = 0; i < size; i++) {
            int u = b[i] & 255;
                if (u < 16) {
                    h.append("0" + Integer.toHexString(u));
                }
               else {
                    h.append(Integer.toHexString(u));
               }
           }
      //clau encriptada
      return h.toString();
    }
    
    private void buttonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistrarActionPerformed
        // TODO add your handling code here:
         //Fem la connexió amb la classe que es connecta amb el servidor
        TFClient l = new TFClientImple();
        //variable Contrasenya que l'encriptem amb el metode MD5
        char clave[]=textContrasenya.getPassword();
        String clavedef=new String(clave);
        try {
            clavedef = md5(textContrasenya.getText());
            System.out.println("Encriptat: "+clavedef);
        } catch (Exception ex) {
            Logger.getLogger(registrar.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Variables per transformar  a Sting
        String usuari = textNomusuari.getText();
        String email = textEmail.getText();
        String tipus = tipusUsuari.getSelectedItem().toString();
        
        //Comprovar si l'usuari a crea ja existeix
        boolean res2 = l.login(usuari,clavedef);
        if(res2){
            JOptionPane.showMessageDialog(rootPane, "Usuari ja existeix.");
                System.out.println("Usuari ja existeix");
                this.textNomusuari.setText("");
                this.textContrasenya.setText("");
                this.textEmail.setText("");
                this.tipusUsuari.setSelectedItem("");
        }
        else{
        // comprovem que ens retorni true o false les dades introduides
        boolean res = l.newUser(usuari,email,clavedef, tipus);
        System.out.println("Resposta a les dades: "+res);
        // Mostrem les dades per veure que s'han introduit correctament
        System.out.println("Usuari: "+ usuari);
        System.out.println("Contrasenya: "+ clavedef);
        System.out.println("Email: "+ email);
        System.out.println("Tipus: "+ tipus);

        // Si es true mostrem missatge que s'ha creat l'usuari correctament si es false no
        if(res){
            JOptionPane.showMessageDialog(rootPane, "Usuari creat correctament.");
                System.out.println("S'ha creat un nou usuari");
                 ArrayList<UserDTO> users = l.listUsers();
                DefaultTableModel modelo = new DefaultTableModel();
                jTable2.setModel(modelo);

                modelo.addColumn("ID");
                modelo.addColumn("NOMBRE");
                modelo.addColumn("CORREU");
                modelo.addColumn("ROLE");

                for (UserDTO user : users) {
                    System.out.println(user.toString());
                    System.out.println("--------------------");
                    Object []ob=new Object[4];
                    ob[0]=(user.getUserId());
                    ob[1]=(user.getUserName());
                    ob[2]=(user.getUserMail());
                    ob[3]=(user.getUserRole());
                    //aafegeixo el model a la taula
                    modelo.addRow(ob);
                }              
        }
        else{
                JOptionPane.showMessageDialog(rootPane, "No s'ha creat correctament l'usuari.");
                System.out.println("No s'ha creat un nou usuari"); 
            } 
        }
    }//GEN-LAST:event_buttonRegistrarActionPerformed

    private void buttonOrdenarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOrdenarAdminActionPerformed
        // TODO add your handling code here:
        //Fem la connexió amb la classe que es connecta amb el servidor
        TFClient l = new TFClientImple();
        //mostrem els usuaris a la taula que nomes son admin
        String tipus = "admin";
         ArrayList<UserDTO> users = l.listUsers(tipus);
                DefaultTableModel modelo = new DefaultTableModel();
                jTable2.setModel(modelo);

                modelo.addColumn("ID");
                modelo.addColumn("NOMBRE");
                modelo.addColumn("CORREU");
                modelo.addColumn("ROLE");

                for (UserDTO user : users) {
                    System.out.println(user.toString());
                    System.out.println("--------------------");
                    Object []ob=new Object[4];
                    ob[0]=(user.getUserId());
                    ob[1]=(user.getUserName());
                    ob[2]=(user.getUserMail());
                    ob[3]=(user.getUserRole());
                    //afegeixo model a la taula
                    modelo.addRow(ob);
                }
    }//GEN-LAST:event_buttonOrdenarAdminActionPerformed

    private void buttonOrdenarTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOrdenarTutorActionPerformed
        // TODO add your handling code here:
        //Fem la connexió amb la classe que es connecta amb el servidor
        TFClient l = new TFClientImple();
        //mostrem els usuaris a la taula que nomes son tutor
        String tipus = "tutor";
         ArrayList<UserDTO> users = l.listUsers(tipus);
                DefaultTableModel modelo = new DefaultTableModel();
                jTable2.setModel(modelo);

                modelo.addColumn("ID");
                modelo.addColumn("NOMBRE");
                modelo.addColumn("CORREU");
                modelo.addColumn("ROLE");

                for (UserDTO user : users) {
                    System.out.println(user.toString());
                    System.out.println("--------------------");
                    Object []ob=new Object[4];
                    ob[0]=(user.getUserId());
                    ob[1]=(user.getUserName());
                    ob[2]=(user.getUserMail());
                    ob[3]=(user.getUserRole());
                    //afegeixo model a la taula
                    modelo.addRow(ob);
                }
    }//GEN-LAST:event_buttonOrdenarTutorActionPerformed

    private void buttonOrdenarStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOrdenarStudentActionPerformed
        // TODO add your handling code here:
        //Fem la connexió amb la classe que es connecta amb el servidor
        TFClient l = new TFClientImple();
        //mostrem els usuaris a la taula que nomes son student
        String tipus = "student";
         ArrayList<UserDTO> users = l.listUsers(tipus);
                DefaultTableModel modelo = new DefaultTableModel();
                jTable2.setModel(modelo);

                modelo.addColumn("ID");
                modelo.addColumn("NOMBRE");
                modelo.addColumn("CORREU");
                modelo.addColumn("ROLE");

                for (UserDTO user : users) {
                    System.out.println(user.toString());
                    System.out.println("--------------------");
                    Object []ob=new Object[4];
                    ob[0]=(user.getUserId());
                    ob[1]=(user.getUserName());
                    ob[2]=(user.getUserMail());
                    ob[3]=(user.getUserRole());
                    //afegeixo model a la taula
                    modelo.addRow(ob);
                }
    }//GEN-LAST:event_buttonOrdenarStudentActionPerformed

    private void buttonOrdenarUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOrdenarUsersActionPerformed
        // TODO add your handling code here:
        //mostrem tots els usuaris a la taula 
        mostrarUsuarisTaula();
    }//GEN-LAST:event_buttonOrdenarUsersActionPerformed

    private void buttonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarActionPerformed
        // TODO add your handling code here:
        //Fem la connexió amb la classe que es connecta amb el servidor
        TFClient l = new TFClientImple();
        ArrayList<UserDTO> users = l.listUsers();
        //variable per guardar nom d'usauri de la fila seleccionada
        String identificador = "";
        for (Object user : users) {
            System.out.println(user.toString());
        }
        int filaSeleccionada = this.jTable2.getSelectedRow();
        if(filaSeleccionada>=0){
                    //Recullim el nom de la fila marcada
                    identificador   = (String)this.jTable2.getValueAt(filaSeleccionada, 1);
                    System.out.println("Identificador: " + identificador);
                }
        boolean ret = l.delUser(identificador);
        //Si ens retorna true l'usuari eliminem l'usuari de la taula i la base de dades
        if (ret) {
            //Eliminar usuari seleccionat a la taula
            DefaultTableModel m = (DefaultTableModel) jTable2.getModel();
            m.removeRow(filaSeleccionada);
            JOptionPane.showMessageDialog(rootPane, "S'ha eliminat l'usuari satisfactoriament.");
            System.out.println("S'ha eliminat l'usuari satisfactoriament.");
        } else {
            JOptionPane.showMessageDialog(rootPane, "NO s'ha eliminat l'usuari satisfactoriament.");
            System.out.println("NO s'ha eliminat l'usuari.");
        }
    }//GEN-LAST:event_buttonEliminarActionPerformed

    private void buttonCercarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCercarActionPerformed
        // TODO add your handling code here:
        //Fem la connexió amb la classe que es connecta amb el servidor
        TFClient l = new TFClientImple();
        String usuari= textCercarUsuari.getText();
        System.out.println("Usuari: "+ usuari);
            System.out.println("DADES TORNADES: " + l.userData(usuari));
            JOptionPane.showMessageDialog(rootPane, "Usuari Trobat.");
            DefaultTableModel modelo = new DefaultTableModel();
            jTable2.setModel(modelo);
            //Fem que mostri les dades de l'usuari que ha cercat
                modelo.addColumn("ID");
                modelo.addColumn("NOMBRE");
                modelo.addColumn("CORREU");
                modelo.addColumn("ROLE");
                    Object []ob=new Object[4];
                    ob[0]=(l.userData(usuari).getUserId());
                    ob[1]=(l.userData(usuari).getUserName());
                    ob[2]=(l.userData(usuari).getUserPswd());
                    ob[3]=(l.userData(usuari).getUserRole());
                    //Afegir model a la taula
                    modelo.addRow(ob);
                    this.textCercarUsuari.setText("");
    }//GEN-LAST:event_buttonCercarActionPerformed

    private void buttonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModificarActionPerformed
        // TODO add your handling code here:
        //Fem la connexio i modifiquem les dades
        TFClient l = new TFClientImple();
        String usuari = textNomusuari.getText();
        String email = textEmail.getText();
        String tipus = tipusUsuari.getSelectedItem().toString();
        Integer id = (Integer)this.jTable2.getValueAt(filaSeleccionada, 0);

        //Comprovem si ens retorna true o false
        boolean ret = l.editUser(id, usuari, email, tipus);
            if(filaSeleccionada != -1){
              jTable2.setValueAt(textNomusuari.getText(), filaSeleccionada, 1);
              jTable2.setValueAt(textEmail.getText(), filaSeleccionada, 2);
              jTable2.setValueAt(tipusUsuari.getSelectedItem(), filaSeleccionada, 3);
              
                System.out.println("Nom Usuari: "+jTable2.getValueAt(filaSeleccionada,1).toString());
                System.out.println("Correu: "+jTable2.getValueAt(filaSeleccionada,2).toString());
                System.out.println("Role: "+jTable2.getValueAt(filaSeleccionada,3).toString());
                
              if(ret){
                  System.out.println("ret: "+ret);
                  JOptionPane.showMessageDialog(rootPane, "Dades modificades!");
              }
              else{
                  System.out.println("error ret: "+ret);
                  JOptionPane.showMessageDialog(rootPane, "Error, No s'ha modificat cap dada");
              }
          }
          else{
              JOptionPane.showMessageDialog(rootPane, "No has seleccionat cap fila");  
              System.out.println("No has seleccionat cap fila");
          }
        
    }//GEN-LAST:event_buttonModificarActionPerformed

    private void carregarDadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carregarDadesActionPerformed
        // TODO add your handling code here:
        //Fem que carregui les dades del usauri seleccionat a la taula per poder modificar les dades
        filaSeleccionada = jTable2.getSelectedRow();
        if(filaSeleccionada != -1){
                this.textNomusuari.setText("");
                this.textContrasenya.setText("");
                this.textEmail.setText("");
                this.tipusUsuari.setSelectedItem("");
                
                textNomusuari.setText(jTable2.getValueAt(filaSeleccionada,1).toString());
                textEmail.setText(jTable2.getValueAt(filaSeleccionada,2).toString());
                tipusUsuari.setSelectedItem(jTable2.getValueAt(filaSeleccionada,3).toString());
                
                System.out.println("Nom Usuari: "+jTable2.getValueAt(filaSeleccionada,1).toString());
                System.out.println("Correu: "+jTable2.getValueAt(filaSeleccionada,2).toString());
                System.out.println("Role: "+jTable2.getValueAt(filaSeleccionada,3).toString());
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "No has seleccionat cap fila");
        }
    }//GEN-LAST:event_carregarDadesActionPerformed

    
    private void buttonCanviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCanviarActionPerformed
        // TODO add your handling code here:
        //Fem la connexió per poder canviar la contrasenya
        TFClient client = new TFClientImple();
        UserDTO userDTO = null;
        //Variables per Encriptar la contrasenya
        char clave[]=textContrasenya.getPassword();
        String clavedef=new String(clave);
        try {
            clavedef = md5(textContrasenya.getText());
            System.out.println("Encriptat: "+clavedef);
        } catch (Exception ex) {
            Logger.getLogger(gestioUsuaris.class.getName()).log(Level.SEVERE, null, ex);
        }
        //variable per passar a string
        String usuari = textNomusuari.getText();

        //Retorna true o false per editar el password
        boolean ret = client.editUserPswd(usuari, clavedef);
        if (ret) {
            if(usuari.equals("") || usuari.equals("null") || clavedef.equals("") || clavedef.equals("null")){
                JOptionPane.showMessageDialog(rootPane, "Error al canviar la contrasenya");
                System.out.println("Error al canviar la contrasenya");
            }
            else {
                userDTO = client.userData(usuari);
                System.out.println("CLAVEDEF2: "+ clavedef);

                System.out.println(userDTO.toString());
                JOptionPane.showMessageDialog(rootPane, "Contrasenya Canviada");
                System.out.println("Contrasenya canviada");
            }
        }
    }//GEN-LAST:event_buttonCanviarActionPerformed

    private void textNomusuariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomusuariActionPerformed
        // TODO add your handling code here:
        //Controlar que el usuari ha de contenir minim 6 caracters
        int numero=5;
        if (textNomusuari.getText().length()<=numero){
            //evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ha de contenir 6 caracters o mes");
        }
    }//GEN-LAST:event_textNomusuariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestioUsuaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestioUsuaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestioUsuaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestioUsuaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestioUsuaris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCanviar;
    private javax.swing.JButton buttonCercar;
    private javax.swing.JButton buttonEliminar;
    private javax.swing.JButton buttonModificar;
    private javax.swing.JButton buttonNou;
    private javax.swing.JButton buttonOrdenarAdmin;
    private javax.swing.JButton buttonOrdenarStudent;
    private javax.swing.JButton buttonOrdenarTutor;
    private javax.swing.JButton buttonOrdenarUsers;
    private javax.swing.JButton buttonRegistrar;
    private javax.swing.JButton buttonTornar;
    private javax.swing.JButton carregarDades;
    private javax.swing.JLabel fons;
    private javax.swing.JLabel icon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelCercar;
    private javax.swing.JLabel labelContrasenya;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelNomusuari;
    private javax.swing.JLabel labelOrdenar;
    private javax.swing.JLabel labelTipusUsuari;
    private javax.swing.JLabel labelTitol;
    private javax.swing.JTextField textCercarUsuari;
    private javax.swing.JPasswordField textContrasenya;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textNomusuari;
    private javax.swing.JComboBox<String> tipusUsuari;
    // End of variables declaration//GEN-END:variables

    //Metode que mostra els usuaris nomes entrar a la pantalla del menu principal de admin.
    private void mostrarUsuarisTaula() {
        TFClient l = new TFClientImple();
         ArrayList<UserDTO> users = l.listUsers();
                DefaultTableModel modelo = new DefaultTableModel();
                jTable2.setModel(modelo);

                modelo.addColumn("ID");
                modelo.addColumn("NOMBRE");
                modelo.addColumn("CORREU");
                modelo.addColumn("ROLE");
                

                for (UserDTO user : users) {
                    System.out.println(user.toString());
                    System.out.println("--------------------");
                    Object []ob=new Object[4];
                    ob[0]=(user.getUserId());
                    ob[1]=(user.getUserName());
                    ob[2]=(user.getUserMail());
                    ob[3]=(user.getUserRole());
                    //añado el modelo a la tabla
                    modelo.addRow(ob);
                }
                
                
                
    }
}
