/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ioc.dam.m13.tutor_finder.desktop;

/**
 *
 * @author Alexandre
 */
public class menuPrincipalAdmin extends javax.swing.JFrame {

    /**
     * Creates new form menuPrincipal
     */
    public menuPrincipalAdmin() {
        initComponents();
        System.out.println("Administrador");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /**
     * Al initComponents tenim els titols i botons de la part del Menu Administrador
     * */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelRol = new javax.swing.JLabel();
        buttonSortir = new javax.swing.JButton();
        labelTitol = new javax.swing.JLabel();
        labelPublicacions = new javax.swing.JLabel();
        labelUsuaris1 = new javax.swing.JLabel();
        buttonUsuaris1 = new javax.swing.JButton();
        gestioPublicacions = new javax.swing.JButton();
        fons = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelRol.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelRol.setText("Admin");
        getContentPane().add(labelRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 600, -1, -1));

        buttonSortir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonSortir.setText("Sortir");
        buttonSortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSortirActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSortir, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 600, 140, 40));

        labelTitol.setFont(new java.awt.Font("Gigi", 0, 105)); // NOI18N
        labelTitol.setText("TutorFinder");
        getContentPane().add(labelTitol, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 540, 90));

        labelPublicacions.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 24)); // NOI18N
        labelPublicacions.setForeground(new java.awt.Color(0, 0, 204));
        labelPublicacions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPublicacions.setText("Gestió de Publicacions");
        getContentPane().add(labelPublicacions, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 370, 270, -1));

        labelUsuaris1.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 24)); // NOI18N
        labelUsuaris1.setForeground(new java.awt.Color(0, 0, 204));
        labelUsuaris1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUsuaris1.setText("Gestió d'Usuaris");
        getContentPane().add(labelUsuaris1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 210, -1));

        buttonUsuaris1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ioc/dam/m13/tutor_finder/desktop/usuario.jpg"))); // NOI18N
        buttonUsuaris1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUsuaris1ActionPerformed(evt);
            }
        });
        getContentPane().add(buttonUsuaris1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 170, 170));

        gestioPublicacions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ioc/dam/m13/tutor_finder/desktop/llistarPublicacions.png"))); // NOI18N
        gestioPublicacions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestioPublicacionsActionPerformed(evt);
            }
        });
        getContentPane().add(gestioPublicacions, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 410, 170, 170));

        fons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ioc/dam/m13/tutor_finder/desktop/fondo.jpg"))); // NOI18N
        getContentPane().add(fons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Botó per sortir de l'aplicació
     * */
    private void buttonSortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSortirActionPerformed
        // TODO add your handling code here:
        //Boto per sortir de l'aplicacio
        System.exit(0);
    }//GEN-LAST:event_buttonSortirActionPerformed

    private void buttonUsuaris1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUsuaris1ActionPerformed
        // TODO add your handling code here:
        //Boto per anar a la pantalla que ens permetra la gestio d'usuaris
        gestioUsuaris formMenuGestioUsuaris = new gestioUsuaris();
        formMenuGestioUsuaris.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonUsuaris1ActionPerformed

    private void gestioPublicacionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestioPublicacionsActionPerformed
        // TODO add your handling code here:
        //Boto per anar a la pantalla que ens permetra la gestio de les publicacions
        gestioPublicacions formMenuGestioPublicacions = new gestioPublicacions();
        formMenuGestioPublicacions.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gestioPublicacionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuPrincipalAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSortir;
    private javax.swing.JButton buttonUsuaris1;
    private javax.swing.JLabel fons;
    private javax.swing.JButton gestioPublicacions;
    private javax.swing.JLabel labelPublicacions;
    private javax.swing.JLabel labelRol;
    private javax.swing.JLabel labelTitol;
    private javax.swing.JLabel labelUsuaris1;
    // End of variables declaration//GEN-END:variables
}
