/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ioc.dam.m13.tutor_finder.desktop;

import ioc.dam.m13.tutor_finder.client.TFClient;
import ioc.dam.m13.tutor_finder.client.TFClientImple;
import static ioc.dam.m13.tutor_finder.desktop.login.UserID;
import ioc.dam.m13.tutor_finder.dtos.AdDTO;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alexandre
 */
public class menuPrincipalClient extends javax.swing.JFrame {
        //variable per saber quina fila de la taula s'ha seleccionat
        int filaSeleccionada = -1;
        //variable per saber el nom del usuari que ha accedit
        String userName;
    /**
     * Creates new form menuPrincipal
     */
    public menuPrincipalClient() {
        initComponents();
        System.out.println("Student");
        
        //fer que automaticament faci el salt de linea alhora d'escriure.
        jTextAreaDescripcio.setLineWrap(true);
        
        //metode que mostra les publicacions del usuari que ha accedit i les de tutor a la taula
        mostrarPublicacionsTaula();
        
        //variable per saber quin user id ha accedit a l'aplicació
        int UserID = login.UserID;
        //per saber el nom del usuari que ha accedit a l'aplicació
        userName = login.usuari;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /**
     * Al initComponents tenim els titols i botons de la part del Menu Usuari
     * */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelROl = new javax.swing.JLabel();
        buttonSortie = new javax.swing.JButton();
        labelTitol = new javax.swing.JLabel();
        buttonContrasenya = new javax.swing.JButton();
        buttonDades = new javax.swing.JButton();
        labelPublicacions2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        labelPublicacions3 = new javax.swing.JLabel();
        textTitol = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDescripcio = new javax.swing.JTextArea();
        buttonEditar = new javax.swing.JButton();
        buttonEliminar = new javax.swing.JButton();
        buttonCarregarDades = new javax.swing.JButton();
        textPreu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboCategoria = new javax.swing.JComboBox<>();
        buttonCreateAds = new javax.swing.JButton();
        buttonMostrarPublicacions = new javax.swing.JButton();
        buttonNou = new javax.swing.JButton();
        fons = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelROl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelROl.setText("Student");
        getContentPane().add(labelROl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 610, -1, -1));

        buttonSortie.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonSortie.setText("Sortir");
        buttonSortie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSortieActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSortie, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 610, 120, 30));

        labelTitol.setFont(new java.awt.Font("Gigi", 0, 105)); // NOI18N
        labelTitol.setText("TutorFinder");
        getContentPane().add(labelTitol, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 540, 90));

        buttonContrasenya.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonContrasenya.setText("Canviar Contrasenya");
        buttonContrasenya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonContrasenyaActionPerformed(evt);
            }
        });
        getContentPane().add(buttonContrasenya, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 610, 200, 30));

        buttonDades.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonDades.setText("Canviar Dades Usuari");
        buttonDades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDadesActionPerformed(evt);
            }
        });
        getContentPane().add(buttonDades, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 610, 210, 30));

        labelPublicacions2.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 24)); // NOI18N
        labelPublicacions2.setForeground(new java.awt.Color(0, 0, 204));
        labelPublicacions2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPublicacions2.setText("Crear Publicacions");
        getContentPane().add(labelPublicacions2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 300, 390, 40));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {"", null, null, null},
                {null, "", null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Titol", "Descripció", "Categoria", "Preu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 830, 260));

        labelPublicacions3.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 24)); // NOI18N
        labelPublicacions3.setForeground(new java.awt.Color(0, 0, 204));
        labelPublicacions3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPublicacions3.setText("Publicacions:");
        getContentPane().add(labelPublicacions3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 270, -1));
        getContentPane().add(textTitol, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 380, 260, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Titol: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 380, 50, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Descripció: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 430, 100, -1));

        jTextAreaDescripcio.setColumns(20);
        jTextAreaDescripcio.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDescripcio);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 430, 260, 110));

        buttonEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonEditar.setText("Editar");
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 340, 70, -1));

        buttonEliminar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonEliminar.setText("Eliminar");
        buttonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 340, 80, -1));

        buttonCarregarDades.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonCarregarDades.setText("Carregar Dades");
        buttonCarregarDades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCarregarDadesActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCarregarDades, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 340, 130, -1));

        textPreu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPreuActionPerformed(evt);
            }
        });
        textPreu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textPreuKeyTyped(evt);
            }
        });
        getContentPane().add(textPreu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 580, 260, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Categoria: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 550, 90, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Preu: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 580, 50, -1));

        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                           ", "Física/Química", "Idiomes", "Informàtica", "Electricitat/Mecànica", "Dibuix", "Economía", "Arts escéniques", "Mùsica" }));
        getContentPane().add(comboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 550, 260, -1));

        buttonCreateAds.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonCreateAds.setText("Crear");
        buttonCreateAds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateAdsActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCreateAds, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 340, 70, -1));

        buttonMostrarPublicacions.setText("Mostrar Publicació ");
        buttonMostrarPublicacions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMostrarPublicacionsActionPerformed(evt);
            }
        });
        getContentPane().add(buttonMostrarPublicacions, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 480, -1, -1));

        buttonNou.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonNou.setText("Nou");
        buttonNou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNouActionPerformed(evt);
            }
        });
        getContentPane().add(buttonNou, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 340, 70, -1));

        fons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ioc/dam/m13/tutor_finder/desktop/fondo.jpg"))); // NOI18N
        getContentPane().add(fons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Botó per sortir de l'aplicació
     * */
    private void buttonSortieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSortieActionPerformed
        // TODO add your handling code here:
        //Boto per sortir de l'aplicacio
       System.exit(0);
    }//GEN-LAST:event_buttonSortieActionPerformed

    private void buttonContrasenyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonContrasenyaActionPerformed
        // TODO add your handling code here:
        //Boto per anar a la pantalla que ens permetra canviar la contrasenya
        this.dispose();
        canvi_ContrasenyaClient formMenuCanviContrasenya = new canvi_ContrasenyaClient();
        formMenuCanviContrasenya.setVisible(true);
    }//GEN-LAST:event_buttonContrasenyaActionPerformed

    private void buttonDadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDadesActionPerformed
        // TODO add your handling code here:
        //Boto per anar a la pantalla que ens permetra modificar les dades
        this.dispose();
        modificar_Dades formMenuDades = new modificar_Dades();
        formMenuDades.setVisible(true);
    }//GEN-LAST:event_buttonDadesActionPerformed

    private void buttonCreateAdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateAdsActionPerformed
        // TODO add your handling code here:
        //Fem la connexió per poder crear una publicació
        TFClient l = new TFClientImple();
        //variables per crear una publicació
        String title = textTitol.getText();
        String description = jTextAreaDescripcio.getText();
        String tipus = comboCategoria.getSelectedItem().toString();
        int typeId = l.getAdTypeByName(tipus);
        String preu = textPreu.getText();
        int numEntero = Integer.parseInt(preu);
        
        //comprovem que el titol i la descripció no queda sense omplir
        if(title == null || title.equals("")|| description == null || description.equals("")){
            JOptionPane.showMessageDialog(rootPane, "El camp Titol i Descripció son obligatoris!!" + "\n" +"Un dels dos està sense omplir!");
        }
        else{
            //Comprovem si torna true o false
        boolean res = l.createAd(UserID, title, description, typeId, numEntero);
        System.out.println("RES: "+res);
        //si es true mostrem missatge que s'ha creat l'anunci correctament i el mostrem a la taula
        if(res){
            JOptionPane.showMessageDialog(rootPane, "Anunci creat correctament");
            DefaultTableModel modelo = new DefaultTableModel();
            jTable2.setModel(modelo);

                modelo.addColumn("Ad id");
                modelo.addColumn("Titol");
                modelo.addColumn("Descripcio");
                modelo.addColumn("Categoria");
                modelo.addColumn("Preu");
                modelo.addColumn("Usuari");
            //Aqui mostrem a la taula les publicacions del usuari que ha accedit a l'aplicació 
            ArrayList<AdDTO> ads = l.listAdsByUser(UserID);
            for (AdDTO ad : ads) {
                System.out.println("----- Ads -----");
                System.out.println(ad.toString());
                System.out.println("--------------------");
                    Object []ob=new Object[6];
                    ob[0]=(ad.getAdId());
                    ob[1]=(ad.getAdTittle());
                    ob[2]=(ad.getAdDescription());
                    ob[3]=(ad.getTypesName());
                    ob[4]=(ad.getAdPrice());
                    ob[5]=(ad.getUserName());
                //afegeixo el model a la taula
                modelo.addRow(ob);
            }
            //Aqui mostrem a la taula les publicacions dels tutors. 
            ArrayList<AdDTO> ads1 = l.listAdsByRole(2);
            for (AdDTO ad : ads1) {
                System.out.println("----- Ads -----");
                System.out.println(ad.toString());
                System.out.println("--------------------");
                    Object []ob=new Object[6];
                    ob[0]=(ad.getAdId());
                    ob[1]=(ad.getAdTittle());
                    ob[2]=(ad.getAdDescription());
                    ob[3]=(ad.getTypesName());
                    ob[4]=(ad.getAdPrice());
                    ob[5]=(ad.getUserName());
                //afegeixo el model a la taula
                modelo.addRow(ob);
            }
        }
        else{
            //Si es false mostrem un missatge que no s'ha creat l'anunci
            JOptionPane.showMessageDialog(rootPane, "No s'ha creat correctament l'anunci.");
            System.out.println("No s'ha creat correctament l'anunci");
        }
        }
    }//GEN-LAST:event_buttonCreateAdsActionPerformed

    private void buttonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarActionPerformed
        // TODO add your handling code here:
        //Fem la connexió amb la classe que es connecta amb el servidor
        TFClient l = new TFClientImple();
        ArrayList<AdDTO> ads = l.listAds();
        //variable per guardar el id de l'anunci de la fila seleccionada
        int identificador = 0;
        //variable per guardar el nom d'uuari que ha accedit a l'aplicació
        String usuari = "";
        for (Object ad : ads) {
            System.out.println(ad.toString());
        }
        filaSeleccionada = this.jTable2.getSelectedRow();
        if(filaSeleccionada>=0){
                    //Recullim el id i el nom d'usuari de la fila marcada
                    identificador   = (int) jTable2.getValueAt(filaSeleccionada, 0);
                    usuari   = (String) jTable2.getValueAt(filaSeleccionada, 5);
                }
        //Comprovem que l'usuari que ha accedit es el mateix de la publicació que es vol eliminar, si no es el mateix no deixem que s'elimini la publicació
        if( userName.equals(usuari) ){
            //Si ens retorna true l'usuari eliminem l'usuari de la taula i la base de dades
             boolean ret = l.delAd(identificador);
            //Eliminar anunci seleccionat a la taula
            DefaultTableModel m = (DefaultTableModel) jTable2.getModel();
            m.removeRow(filaSeleccionada);
            JOptionPane.showMessageDialog(rootPane, "S'ha eliminat l'anunci satisfactoriament.");
            System.out.println("S'ha eliminat l'anunci satisfactoriament.");
            
        } else {
            JOptionPane.showMessageDialog(rootPane, "NO s'ha eliminat l'anunci satisfactoriament." + "\n" + "Només podeu eliminar anuncis creats per vosaltres!");
            System.out.println("NO s'ha eliminat l'anunci.");
         }
    }//GEN-LAST:event_buttonEliminarActionPerformed

    private void buttonCarregarDadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCarregarDadesActionPerformed
        // TODO add your handling code here:
        //Fem que carregui les dades del usauri seleccionat a la taula per poder modificar les dades
        filaSeleccionada = jTable2.getSelectedRow();
        if(filaSeleccionada != -1){
            //Fiquem els camps en blanc per posteriorment carregar les dades de la fila seleccionada
                this.textTitol.setText("");
                this.jTextAreaDescripcio.setText("");
                this.comboCategoria.setSelectedItem("");
                this.textPreu.setText("");
                textTitol.setText(jTable2.getValueAt(filaSeleccionada,1).toString());
                jTextAreaDescripcio.setText(jTable2.getValueAt(filaSeleccionada,2).toString());
                comboCategoria.setSelectedItem(jTable2.getValueAt(filaSeleccionada,3).toString());
                textPreu.setText(jTable2.getValueAt(filaSeleccionada,4).toString());
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "No has seleccionat cap fila");
        }
    }//GEN-LAST:event_buttonCarregarDadesActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        // TODO add your handling code here:
        //Fem la connexio i modifiquem les dades
        
        TFClient l = new TFClientImple();
        String title = textTitol.getText();
        String description = jTextAreaDescripcio.getText();
        String tipus = comboCategoria.getSelectedItem().toString();
        int typeId = l.getAdTypeByName(tipus);
        String preu = textPreu.getText();
        int numEntero = Integer.parseInt(preu);
        int id = (int)this.jTable2.getValueAt(filaSeleccionada, 0);
        
        System.out.println("id ad: " + id);
        System.out.println("id ad: " + title);
        System.out.println("id ad: " + description);
        System.out.println("id ad: " + typeId);
        System.out.println("id ad: " + numEntero);

        //Comprovem si ens retorna true o false
        l.editAd(id, title, description, typeId, numEntero);
        //System.out.println("RET: " + ret);   
        JOptionPane.showMessageDialog(rootPane, "Dades Modificades");
        mostrarPublicacionsTaula();
    }//GEN-LAST:event_buttonEditarActionPerformed

    private void textPreuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPreuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPreuActionPerformed

    private void textPreuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPreuKeyTyped
        // TODO add your handling code here:
        //Comprovem que al camp preu no pot introduir lletres només numeros.
        int k=(int)evt.getKeyChar();
        if (k >= 97 && k <= 122 || k>=65 && k<=90){
        evt.setKeyChar((char)KeyEvent.VK_CLEAR);
        JOptionPane.showMessageDialog(null,"No pots introduir lletres!!!","Error de Dades",JOptionPane.ERROR_MESSAGE);
        }
        if(k==241 || k==209){
        evt.setKeyChar((char)KeyEvent.VK_CLEAR);
        JOptionPane.showMessageDialog(null,"No pots introduir lletres!!!","Error de Dades",JOptionPane.ERROR_MESSAGE);
        }
        if(k==10){
        textPreu.transferFocus();
        }
    }//GEN-LAST:event_textPreuKeyTyped

    private void buttonMostrarPublicacionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMostrarPublicacionsActionPerformed
        // TODO add your handling code here:
        //boto que ens mostrara la publicació per poder-la llegir al complert
        mostrarPublicacio m = new mostrarPublicacio();
        this.dispose();
        filaSeleccionada = jTable2.getSelectedRow();
        m.textTitol.setText(jTable2.getValueAt(filaSeleccionada,1).toString());;
        m.jTextAreaDescripcio.setText(jTable2.getValueAt(filaSeleccionada,2).toString());
        m.comboCategoria.setSelectedItem(jTable2.getValueAt(filaSeleccionada,3).toString());
        m.textPreu.setText(jTable2.getValueAt(filaSeleccionada,4).toString());
        m.show();
    }//GEN-LAST:event_buttonMostrarPublicacionsActionPerformed

    private void buttonNouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNouActionPerformed
        // TODO add your handling code here:
        //Fiquem en blanc els camps per crear un nou anunci
        this.textTitol.setText("");
        this.jTextAreaDescripcio.setText("");
        this.textPreu.setText("");
        this.comboCategoria.setSelectedItem("");
    }//GEN-LAST:event_buttonNouActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuPrincipalClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuPrincipalClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuPrincipalClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuPrincipalClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
     

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuPrincipalClient().setVisible(true);
            }
        });
    }
    
    //Metode que mostra els anuncis nomes entrar a la pantalla del menu principal student.
    private void mostrarPublicacionsTaula() {
        
         TFClient l = new TFClientImple();
         DefaultTableModel modelo = new DefaultTableModel();
                jTable2.setModel(modelo);

                modelo.addColumn("Ad id");
                modelo.addColumn("Titol");
                modelo.addColumn("Descripcio");
                modelo.addColumn("Categoria");
                modelo.addColumn("Preu");
                modelo.addColumn("Usuari");

                //Aqui mostrem la llista de publicacions dels usuaris que ha accedit a l'aplicació
                ArrayList<AdDTO> ads = l.listAdsByUser(UserID);
                for (AdDTO ad : ads) {
                System.out.println("----- Ads -----");
                System.out.println(ad.toString());
                System.out.println("--------------------");
                    Object []ob=new Object[6];
                    ob[0]=(ad.getAdId());
                    ob[1]=(ad.getAdTittle());
                    ob[2]=(ad.getAdDescription());
                    ob[3]=(ad.getTypesName());
                    ob[4]=(ad.getAdPrice());
                    ob[5]=(ad.getUserName());
                    //aafegeixo el model a la taula
                    modelo.addRow(ob);
                }
                //Aqui mostrem la llista de publicacions del tutors
                 ArrayList<AdDTO> ads1 = l.listAdsByRole(2);
                for (AdDTO ad : ads1) {
                System.out.println("----- Ads -----");
                System.out.println(ad.toString());
                System.out.println("--------------------");
                    Object []ob=new Object[6];
                    ob[0]=(ad.getAdId());
                    ob[1]=(ad.getAdTittle());
                    ob[2]=(ad.getAdDescription());
                    ob[3]=(ad.getTypesName());
                    ob[4]=(ad.getAdPrice());
                    ob[5]=(ad.getUserName());
                    //aafegeixo el model a la taula
                    modelo.addRow(ob);
                }     
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCarregarDades;
    private javax.swing.JButton buttonContrasenya;
    private javax.swing.JButton buttonCreateAds;
    private javax.swing.JButton buttonDades;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonEliminar;
    private javax.swing.JButton buttonMostrarPublicacions;
    private javax.swing.JButton buttonNou;
    private javax.swing.JButton buttonSortie;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JLabel fons;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextAreaDescripcio;
    private javax.swing.JLabel labelPublicacions2;
    private javax.swing.JLabel labelPublicacions3;
    private javax.swing.JLabel labelROl;
    private javax.swing.JLabel labelTitol;
    private javax.swing.JTextField textPreu;
    private javax.swing.JTextField textTitol;
    // End of variables declaration//GEN-END:variables
}

