/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ioc.dam.m13.tutor_finder.desktop;

/**
 *
 * @author Alexandre
 */
public class menuPrincipalProfessor extends javax.swing.JFrame {

    /**
     * Creates new form menuPrincipal
     */
    public menuPrincipalProfessor() {
        initComponents();
        System.out.println("Tutor");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /**
     * Al initComponents tenim els titols i botons de la part del Menu Usuari
     * */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelROl = new javax.swing.JLabel();
        buttonSortie = new javax.swing.JButton();
        labelTitol = new javax.swing.JLabel();
        buttonContrasenya = new javax.swing.JButton();
        buttonDades = new javax.swing.JButton();
        labelPublicacions2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        labelPublicacions3 = new javax.swing.JLabel();
        labelPublicacions = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        fons = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelROl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelROl.setText("Tutor");
        getContentPane().add(labelROl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 610, -1, -1));

        buttonSortie.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonSortie.setText("Sortir");
        buttonSortie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSortieActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSortie, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 610, 120, 30));

        labelTitol.setFont(new java.awt.Font("Gigi", 0, 105)); // NOI18N
        labelTitol.setText("TutorFinder");
        getContentPane().add(labelTitol, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 540, 90));

        buttonContrasenya.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonContrasenya.setText("Canviar Contrasenya");
        buttonContrasenya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonContrasenyaActionPerformed(evt);
            }
        });
        getContentPane().add(buttonContrasenya, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 610, 200, 30));

        buttonDades.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonDades.setText("Canviar Dades Usuari");
        buttonDades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDadesActionPerformed(evt);
            }
        });
        getContentPane().add(buttonDades, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 610, 210, 30));

        labelPublicacions2.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 24)); // NOI18N
        labelPublicacions2.setForeground(new java.awt.Color(0, 0, 204));
        labelPublicacions2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPublicacions2.setText("Crear Publicacions");
        getContentPane().add(labelPublicacions2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 270, 390, 40));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Titol", "Descripció", "Categoria", "Preu"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 700, 260));

        labelPublicacions3.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 24)); // NOI18N
        labelPublicacions3.setForeground(new java.awt.Color(0, 0, 204));
        labelPublicacions3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPublicacions3.setText("Publicacions:");
        getContentPane().add(labelPublicacions3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 270, -1));

        labelPublicacions.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 24)); // NOI18N
        labelPublicacions.setForeground(new java.awt.Color(0, 0, 204));
        labelPublicacions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPublicacions.setText("Llistar: ");
        getContentPane().add(labelPublicacions, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, 110, -1));

        jButton4.setText("Totes");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, 130, -1));

        jButton5.setText("Informàtica");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, 130, -1));

        jButton6.setText("Economia");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 130, -1));

        jButton7.setText("Musica");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, 130, -1));

        jButton8.setText("Fisica/Quimica");
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 130, -1));

        jButton9.setText("Dibux");
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 470, 130, -1));

        jButton10.setText("Electricitat/Mecanica");
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, 130, -1));

        jButton11.setText("Idiomes");
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 530, 130, -1));

        jButton12.setText("Arts Esceniques");
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 560, 130, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 360, 260, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Titol: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 360, 50, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Descripció: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 390, 100, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 390, 260, 110));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Editar");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 320, 70, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Eliminar");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 320, 80, -1));

        jButton13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton13.setText("Crear");
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 320, 70, -1));

        jButton14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton14.setText("Carregar Dades");
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 320, 130, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 540, 260, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Categoria: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 510, 90, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Preu: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 540, 50, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                    ", "Informàtica", "Economia", "Musica", "Fisica/Quimica", "Dibuix", "Electricitat/Mecanica", "Idiomes", "Arts Esceniques" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 510, 260, -1));

        fons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ioc/dam/m13/tutor_finder/desktop/fondo.jpg"))); // NOI18N
        getContentPane().add(fons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Botó per sortir de l'aplicació
     * */
    private void buttonSortieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSortieActionPerformed
        // TODO add your handling code here:
        //Boto per sortir de l'aplicacio
       System.exit(0);
    }//GEN-LAST:event_buttonSortieActionPerformed

    private void buttonContrasenyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonContrasenyaActionPerformed
        // TODO add your handling code here:
        //Boto per anar a la pantalla que ens permetra canviar la contrasenya
        this.dispose();
        canvi_ContrasenyaProfessor formMenuCanviContrasenya = new canvi_ContrasenyaProfessor();
        formMenuCanviContrasenya.setVisible(true);
    }//GEN-LAST:event_buttonContrasenyaActionPerformed

    private void buttonDadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDadesActionPerformed
        // TODO add your handling code here:
        //Boto per anar a la pantalla que ens permetra modificar les dades
        this.dispose();
        modificar_Dades formMenuDades = new modificar_Dades();
        formMenuDades.setVisible(true);
    }//GEN-LAST:event_buttonDadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuPrincipalProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuPrincipalProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuPrincipalProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuPrincipalProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
               
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuPrincipalProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonContrasenya;
    private javax.swing.JButton buttonDades;
    private javax.swing.JButton buttonSortie;
    private javax.swing.JLabel fons;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel labelPublicacions;
    private javax.swing.JLabel labelPublicacions2;
    private javax.swing.JLabel labelPublicacions3;
    private javax.swing.JLabel labelROl;
    private javax.swing.JLabel labelTitol;
    // End of variables declaration//GEN-END:variables
}
