/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ioc.dam.m13.tutor_finder.desktop;

import javax.swing.JOptionPane;
import ioc.dam.m13.tutor_finder.client.TFClient;
import ioc.dam.m13.tutor_finder.client.TFClientImple;
import ioc.dam.m13.tutor_finder.dtos.UserDTO;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Alexandre
 */
public class modificar_Dades extends javax.swing.JFrame {

    /**
     * Creates new form canvi_Contrasenya
     */
    public modificar_Dades() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitol = new javax.swing.JLabel();
        buttonTornar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buttonModificar = new javax.swing.JButton();
        labelNomusuari = new javax.swing.JLabel();
        textNomusuari = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        tipusUsuari = new javax.swing.JComboBox<>();
        labelTipusUsuari = new javax.swing.JLabel();
        buttorCarregar = new javax.swing.JButton();
        fons = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitol.setFont(new java.awt.Font("Gigi", 0, 105)); // NOI18N
        labelTitol.setText("TutorFinder");
        getContentPane().add(labelTitol, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 540, 90));

        buttonTornar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonTornar.setText("Tornar");
        buttonTornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTornarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonTornar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 590, 120, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ioc/dam/m13/tutor_finder/desktop/canvi contrasenya.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 330, -1, -1));

        buttonModificar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonModificar.setText("Modificar");
        buttonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModificarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 590, 120, 30));

        labelNomusuari.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelNomusuari.setText("Nom usuari: ");
        getContentPane().add(labelNomusuari, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, -1, -1));

        textNomusuari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomusuariActionPerformed(evt);
            }
        });
        getContentPane().add(textNomusuari, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 240, -1));

        labelEmail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelEmail.setText("E-mail: ");
        getContentPane().add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, -1, -1));

        textEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmailActionPerformed(evt);
            }
        });
        getContentPane().add(textEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, 240, -1));

        tipusUsuari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "            ", "student", "tutor" }));
        getContentPane().add(tipusUsuari, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 530, 240, -1));

        labelTipusUsuari.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelTipusUsuari.setText("Tipus d'usuari: ");
        getContentPane().add(labelTipusUsuari, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, -1, -1));

        buttorCarregar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttorCarregar.setText("Carregar Dades");
        buttorCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttorCarregarActionPerformed(evt);
            }
        });
        getContentPane().add(buttorCarregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 160, 30));

        fons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ioc/dam/m13/tutor_finder/desktop/fondo.jpg"))); // NOI18N
        getContentPane().add(fons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTornarActionPerformed
        // TODO add your handling code here:
        //Botó per tornar al menu students
        menuPrincipalClient formMenuClient = new menuPrincipalClient();
        formMenuClient.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonTornarActionPerformed

    private void buttonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModificarActionPerformed
        // TODO add your handling code here:
        //Fem la connexió i modifiquem les dades
        TFClient client = new TFClientImple();
        UserDTO userDTO = null;
        String usuari = textNomusuari.getText();
        String email = textEmail.getText();
        String tipus = tipusUsuari.getSelectedItem().toString();
            userDTO = client.userData(usuari);
            boolean ret = client.editUser(userDTO.getUserId(), usuari, email, tipus);
            if(ret){
                System.out.println("RET: "+ret);
                JOptionPane.showMessageDialog(rootPane, "Dades Modificades!");
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Error no s'ha modificat cap dada!");
            }  
    }//GEN-LAST:event_buttonModificarActionPerformed

    private void textNomusuariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomusuariActionPerformed
        // TODO add your handling code here:
        //Controlar que el usuari ha de contenir minim 6 caracters
        int numero=5;
        if (textNomusuari.getText().length()<=numero){
            //evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ha de contenir 6 caracters o mes");
        }
    }//GEN-LAST:event_textNomusuariActionPerformed

    private void textEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmailActionPerformed
        // TODO add your handling code here:
        //Controlar que el format del email sigui correcte
        Pattern pattern = Pattern
        .compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
            + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        Matcher mather = pattern.matcher(textEmail.getText());

        if (mather.find() == true) {
            System.out.println("El email introduit es correcte.");
            JOptionPane.showMessageDialog(rootPane, "El email introduit es correcte.");
        } else {
            System.out.println("El email introduit NO es correcte.");
            JOptionPane.showMessageDialog(rootPane, "El email introduit NO es correcte.");
        }
    }//GEN-LAST:event_textEmailActionPerformed

    private void buttorCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttorCarregarActionPerformed
                // TODO add your handling code here:
                //Fem la connexió i carreguem les dades del usuari que volem modificar dades
                TFClient client = new TFClientImple();
                String usuari = textNomusuari.getText();
                UserDTO user = client.userData(usuari);
                String userName = user.getUserName();
                String userEmail = user.getUserMail();
                String userRole = user.getUserRole();

                    System.out.println("Usuari: ");
                    System.out.println("--------------------");
                    System.out.println(userName);
                    System.out.println(userEmail);
                    System.out.println(userRole); 
                  
                textNomusuari.setText(userName);
                textEmail.setText(userEmail);
                tipusUsuari.setSelectedItem(userRole);
                
    }//GEN-LAST:event_buttorCarregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modificar_Dades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modificar_Dades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modificar_Dades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modificar_Dades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modificar_Dades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonModificar;
    private javax.swing.JButton buttonTornar;
    private javax.swing.JButton buttorCarregar;
    private javax.swing.JLabel fons;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelNomusuari;
    private javax.swing.JLabel labelTipusUsuari;
    private javax.swing.JLabel labelTitol;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textNomusuari;
    private javax.swing.JComboBox<String> tipusUsuari;
    // End of variables declaration//GEN-END:variables
}
