/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ioc.dam.m13.tutor_finder.desktop;

import ioc.dam.m13.tutor_finder.client.TFClient;
import ioc.dam.m13.tutor_finder.client.TFClientImple;
import ioc.dam.m13.tutor_finder.dtos.UserDTO;
import java.security.MessageDigest;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexandre
 */
public class registrar extends javax.swing.JFrame {

    /**
     * Creates new form registrar
     */
    public registrar() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitol = new javax.swing.JLabel();
        labelNomusuari = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelContrasenya = new javax.swing.JLabel();
        textContrasenya = new javax.swing.JPasswordField();
        textEmail = new javax.swing.JTextField();
        buttonRegistrar = new javax.swing.JButton();
        textNomusuari = new javax.swing.JTextField();
        buttonSortir = new javax.swing.JButton();
        buttonTornar = new javax.swing.JButton();
        labelTipusUsuari = new javax.swing.JLabel();
        tipusUsuari = new javax.swing.JComboBox<>();
        icono = new javax.swing.JLabel();
        fons = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitol.setFont(new java.awt.Font("Tahoma", 0, 55)); // NOI18N
        labelTitol.setText("Registrar Usuari:");
        getContentPane().add(labelTitol, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, -1, -1));

        labelNomusuari.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelNomusuari.setText("Nom usuari: ");
        getContentPane().add(labelNomusuari, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, -1));

        labelEmail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelEmail.setText("E-mail: ");
        getContentPane().add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, -1, -1));

        labelContrasenya.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelContrasenya.setText("Contrasenya: ");
        getContentPane().add(labelContrasenya, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, -1, -1));

        textContrasenya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textContrasenyaActionPerformed(evt);
            }
        });
        getContentPane().add(textContrasenya, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, 240, -1));

        textEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmailActionPerformed(evt);
            }
        });
        getContentPane().add(textEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 240, -1));

        buttonRegistrar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        buttonRegistrar.setText("Registrar");
        buttonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 360, 50));

        textNomusuari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomusuariActionPerformed(evt);
            }
        });
        getContentPane().add(textNomusuari, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 240, -1));

        buttonSortir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonSortir.setText("Sortir");
        buttonSortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSortirActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSortir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 570, 130, 40));

        buttonTornar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonTornar.setText("Tornar");
        buttonTornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTornarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonTornar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 570, 130, -1));

        labelTipusUsuari.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelTipusUsuari.setText("Tipus d'usuari: ");
        getContentPane().add(labelTipusUsuari, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, -1, -1));

        tipusUsuari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "            ", "student", "tutor" }));
        tipusUsuari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipusUsuariActionPerformed(evt);
            }
        });
        getContentPane().add(tipusUsuari, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 500, 240, -1));

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ioc/dam/m13/tutor_finder/desktop/registre usuari.png"))); // NOI18N
        getContentPane().add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 340, 140, 140));

        fons.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ioc/dam/m13/tutor_finder/desktop/fondo.jpg"))); // NOI18N
        fons.setToolTipText("");
        getContentPane().add(fons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Botó per sortir de l'aplicació
     * */
    private void buttonSortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSortirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttonSortirActionPerformed
    /**
     * Botó per tornar a iniciar sesió 
     * */
    private void buttonTornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTornarActionPerformed
        // TODO add your handling code here:
            login formLogin = new login();
            formLogin.setVisible(true);
            this.dispose();       
    }//GEN-LAST:event_buttonTornarActionPerformed

    private void textEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmailActionPerformed
        // TODO add your handling code here:
        //Controlar que el format del email sigui correcte
        Pattern pattern = Pattern
                .compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        Matcher mather = pattern.matcher(textEmail.getText());
 
        if (mather.find() == true) {
            System.out.println("El email introduit es correcte.");
            JOptionPane.showMessageDialog(rootPane, "El email introduit es correcte.");
        } else {
            System.out.println("El email introduit NO es correcte.");
            JOptionPane.showMessageDialog(rootPane, "El email introduit NO es correcte.");
        }
    }//GEN-LAST:event_textEmailActionPerformed

    private void tipusUsuariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipusUsuariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipusUsuariActionPerformed

    private void textNomusuariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomusuariActionPerformed
        // TODO add your handling code here:
        //Controlar que el usuari ha de contenir minim 6 caracters
        int numero=5;        
        if (textNomusuari.getText().length()<=numero){
            //evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ha de contenir 6 caracters o mes");
        }
    }//GEN-LAST:event_textNomusuariActionPerformed

    private void textContrasenyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textContrasenyaActionPerformed
        // TODO add your handling code here:
        //Controlar que la contrasenya ha de contenir minim 6 caracters
        int numero=5;
        char clave[]=textContrasenya.getPassword();
        String clavedef=new String(clave);        
        if (clavedef.length()<=numero){
            //evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ha de contenir 6 caracters o mes");
        }
    }//GEN-LAST:event_textContrasenyaActionPerformed

    //Metode per encriptar l'String que passem
    public static String md5(String clear) throws Exception {
    MessageDigest md = MessageDigest.getInstance("MD5");
    byte[] b = md.digest(clear.getBytes());
    int size = b.length;
    StringBuffer h = new StringBuffer(size);
        for (int i = 0; i < size; i++) {
            int u = b[i] & 255;
                if (u < 16) {
                    h.append("0" + Integer.toHexString(u));
                }
               else {
                    h.append(Integer.toHexString(u));
               }
           }
      //clau encriptada
      return h.toString();
    }
    
    private void buttonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistrarActionPerformed
        // TODO add your handling code here:
        //Fem la connexió amb la classe que es connecta amb el servidor
        TFClient l = new TFClientImple();
        UserDTO userDTO = new UserDTO();
        //variable Contrasenya que l'encriptem amb el metode MD5
        char clave[]=textContrasenya.getPassword();
        String clavedef=new String(clave);
        try {
            clavedef = md5(textContrasenya.getText());
            System.out.println("Encriptat: "+clavedef);
        } catch (Exception ex) {
            Logger.getLogger(registrar.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Variables per transformar  a Sting
        String usuari = textNomusuari.getText();
        String email = textEmail.getText();
        String tipus = tipusUsuari.getSelectedItem().toString();
        
        //Comprovar si l'usuari a crea ja existeix
        boolean res2 = l.login(usuari,clavedef);
        if(res2){
            userDTO = l.userData(usuari);
            JOptionPane.showMessageDialog(rootPane, "Usuari ja existeix.");
            System.out.println("Usuari ja existeix");
            this.textNomusuari.setText("");
            this.textContrasenya.setText("");
            this.textEmail.setText("");
            this.tipusUsuari.setSelectedItem("");
        }
        else{
            // comprovem que ens retorni true o false les dades introduides
            boolean res = l.newUser(usuari,email,clavedef, tipus);
            System.out.println("Resposta a les dades: "+res);
            // Mostrem les dades per veure que s'han introduit correctament
            System.out.println("Usuari: "+ usuari);
            System.out.println("Contrasenya: "+ clavedef);
            System.out.println("Email: "+ email);
            System.out.println("Tipus: "+ tipus);

            // Si es true mostrem missatge que s'ha creat l'usuari correctament si es false no
            if(res){
                JOptionPane.showMessageDialog(rootPane, "Usuari creat correctament.");
                System.out.println("S'ha creat un nou usuari");
                this.textNomusuari.setText("");
                this.textContrasenya.setText("");
                this.textEmail.setText("");
                this.tipusUsuari.setSelectedItem("");
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "No s'ha creat correctament l'usuari.");
                System.out.println("No s'ha creat un nou usuari");
            }

        }
    }//GEN-LAST:event_buttonRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonRegistrar;
    private javax.swing.JButton buttonSortir;
    private javax.swing.JButton buttonTornar;
    private javax.swing.JLabel fons;
    private javax.swing.JLabel icono;
    private javax.swing.JLabel labelContrasenya;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelNomusuari;
    private javax.swing.JLabel labelTipusUsuari;
    private javax.swing.JLabel labelTitol;
    private javax.swing.JPasswordField textContrasenya;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textNomusuari;
    private javax.swing.JComboBox<String> tipusUsuari;
    // End of variables declaration//GEN-END:variables
}
